ecs_cluster_name = "wutyee-ecs-cluster-prod"
ecs_service_name = "wutyee-ecs-service-prod"
ecs_task_defn_family = "wutyee-ecs-task-def-prod"
ecs_container_name = "wutyee-container-prod"
ecs_port_name = "wutyee-3000-tcp-prod"